apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio-server
  namespace: rstudio
  labels:
    app.kubernetes.io/name: rstudio-server
    app.kubernetes.io/instance: rstudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rstudio-server
      app.kubernetes.io/instance: rstudio
  template:
    metadata:
      name: rstudio-server
      labels:
        app.kubernetes.io/name: rstudio-server
        app.kubernetes.io/instance: rstudio
    spec:
      volumes:
        - name: rstudio-server-config-pv-storage
          persistentVolumeClaim:
            claimName: rstudio-server-config-pv-claim
        - name: rstudio-server-workspace-pv-storage
          persistentVolumeClaim:
            claimName: rstudio-server-workspace-pv-claim
        - name: rstudio-server-packages-pv-storage
          persistentVolumeClaim:
            claimName: rstudio-server-packages-pv-claim
      containers:
        - name: rstudio-server
          image: rocker/rstudio:latest
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rstudio-admin
                  key: admin-password
            - name: ROOT
              value: "false"
            - name: DISABLE_AUTH
              value: "false"
          securityContext:
            privileged: false
          volumeMounts:
            - mountPath: "/home/rstudio/.config/rstudio"
              name: rstudio-server-config-pv-storage
            - mountPath: "/home/rstudio/workspace"
              name: rstudio-server-workspace-pv-storage
            - mountPath: "/usr/local/lib/R/site-library"
              name: rstudio-server-packages-pv-storage
          livenessProbe:
            httpGet:
              path: /
              port: 8787
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rstudio-server-config-pv-claim
  namespace: rstudio
  labels:
    app.kubernetes.io/name: rstudio-server
    app.kubernetes.io/instance: rstudio  
spec:
#  storageClassName: nfs-client # Needs to be specified if no default class is set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rstudio-server-workspace-pv-claim
  namespace: rstudio
  labels:
    app.kubernetes.io/name: rstudio-server
    app.kubernetes.io/instance: rstudio  
spec:
#  storageClassName: nfs-client # Needs to be specified if no default class is set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rstudio-server-packages-pv-claim
  namespace: rstudio
  labels:
    app.kubernetes.io/name: rstudio-server
    app.kubernetes.io/instance: rstudio  
spec:
#  storageClassName: nfs-client # Needs to be specified if no default class is set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rstudio-server
  namespace: rstudio
  labels:
    app.kubernetes.io/name: rstudio-server
    app.kubernetes.io/instance: rstudio
spec:
  selector:
    app.kubernetes.io/name: rstudio-server
    app.kubernetes.io/instance: rstudio
  ports:
    - name: http
      protocol: TCP
      port: 8787
      targetPort: 8787
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rstudio-server-http
  namespace: rstudio
  labels:
    app.kubernetes.io/name: rstudio-server
    app.kubernetes.io/instance: rstudio
spec:
#  ingressClassName: nginx # Needs to be specified if no default class is set
  tls:
  - hosts:
    - <My-Vault-Hostname>
  rules:
  - host: <My-Vault-Hostname>
    http:
      paths:
      - backend:
          service:
            name: rstudio-server
            port:
              number: 8787
        path: /
        pathType: Prefix
---
apiVersion: v1
kind: Secret
metadata:
  name: rstudio-admin
  namespace: rstudio
  labels:
    app.kubernetes.io/name: rstudio-server
    app.kubernetes.io/instance: rstudio
type: Opaque
stringData:
  admin-password: <my-secure-password>
